In [1]:
import tensorflow as tf
print(tf.__version__)

2024-05-05 21:19:50.542299: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-05 21:19:50.543152: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-05 21:19:50.586914: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-05 21:19:50.805371: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-05 21:19:51.529574: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warnin

2.16.1


### Tensor basics

A Tensor is a generalization of a scalar, a vector o a matrix.
- Scalar -> 0 dim
- Vector -> 1 dim
- Matrix -> 2 dim
- Tensor ->  > 2 dim

### Basic operations

Initializations

In [9]:
x = tf.constant(4.0,shape=(1,1),dtype=tf.float32)

In [11]:
# Matrix
x = tf.constant([[1,2,3],[4,5,6]])

In [17]:
x = tf.ones((3,3))
print(x)
x = tf.zeros((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [20]:
x = tf.eye(3) # Identity matrix
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [28]:
x = tf.random.normal((3,3,3),mean=2,stddev=3)
x

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[ 1.0799166 ,  5.049867  , -3.8436556 ],
        [ 3.6847153 ,  4.945138  ,  0.83345616],
        [ 1.2673262 , -2.018952  ,  5.2307377 ]],

       [[ 6.895509  ,  6.535449  ,  0.19544339],
        [ 4.39172   , -2.77635   , -1.8155596 ],
        [ 3.5863926 , -0.28791904, -2.191434  ]],

       [[10.125935  , -2.9023461 , -0.56102014],
        [ 8.794342  ,  5.360751  ,  1.534946  ],
        [ 4.405306  ,  0.35844064,  8.603266  ]]], dtype=float32)>

In [31]:
x = tf.random.uniform((2,3),minval=10,maxval=12)
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[10.824686, 11.039811, 11.121601],
       [10.505914, 11.996078, 10.824968]], dtype=float32)>

In [36]:
x = tf.range(start = 9, limit=21,delta= 2)
x

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 9, 11, 13, 15, 17, 19], dtype=int32)>

In [39]:
x = tf.cast(x,dtype=tf.float64)

In [45]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])


In [48]:
z = tf.add(x,y)
print(z)
z = x + y
print(z)

z = tf.subtract(x,y)
print(z)
z = x-y
print(z)

# same with divide and multiply

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [50]:
# Matrix multiplication

x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

z = x @ y
print(z)
z = tf.matmul(x,y)

tf.Tensor(
[[-0.6400888  -0.70733815  2.8738937   1.4092824 ]
 [ 0.33103928 -2.0588906  -0.31460345  1.3802919 ]], shape=(2, 4), dtype=float32)


In [66]:
x = tf.constant(range(9))
print(x[::-1])

tf.Tensor([8 7 6 5 4 3 2 1 0], shape=(9,), dtype=int32)


In [75]:
# Reshaping
x =tf.range(15)
x = tf.reshape(x,(3,5))
x

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]], dtype=int32)>

In [76]:
x = tf.transpose(x,perm=[1,0])

In [77]:
x

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]], dtype=int32)>